public interface GameProperties {

    int GAME_COURT_HEIGHT = 500;
    int GAME_COURT_WIDTH = 500;
    int TOP_FRAME = 100;
    int BOTTOM_FRAME = 50;
    int LEFT_FRAME = 50;
    int RIGHT_FRAME = 50;
    int GAME_COURT_TOP_LIMIT = TOP_FRAME;
    int GAME_COURT_BOTTOM_LIMIT = GAME_COURT_HEIGHT + TOP_FRAME;
    int GAME_COURT_LEFT_LIMIT = LEFT_FRAME;
    int GAME_COURT_RIGHT_LIMIT = GAME_COURT_WIDTH + LEFT_FRAME;

}
